project_id = "fkmusfeccaozbdbvkdqo"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.create-cod-order]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false
